### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by aripiprazole** [aripiprazole/lura#3]
- [ ] Type System
  - [x] #4
  - [x] #5
  - [x] #6
  - [x] #7
  - [x] #8
  - [x] #9
  - [ ] Trait methods type checking
  - [ ] Class methods type checking
  - [ ] Data methods type checking
  - [ ] Mutual recursive functions on expression-level
  - [ ] Dependent types feature
- [x] #10
  - [ ] Closure conversion
  - [ ] Coverage checking
- [ ] Resolution
  - [ ] Create class fields instead of using direct methods
  - [ ] Add an HIR indexing expression
  - [ ] Improve circular dependency error messages
